// PM2 Ecosystem Configuration
// Generated by PortOS PM2 Standardizer

module.exports = {
  apps: [
    {
      name: 'gradient-play-server',
      cwd: './',
      script: 'server/index.js',
      watch: [
        'server'
      ],
      watch_delay: 1000,
      ignore_watch: [
        'node_modules',
        'server/data',
        '*.log'
      ],
      env: {
        NODE_ENV: 'development',
        TZ: 'UTC',
        PORT: 5572,
        HOST: '127.0.0.1',
        CDP_ENDPOINT: 'http://127.0.0.1:5556',
        GAME_URL: 'https://game.gradient-bang.com'
      }
    },
    {
      name: 'gradient-play-client',
      cwd: './client',
      script: 'node_modules/vite/bin/vite.js',
      args: '--host 0.0.0.0 --port 5571',
      watch: false,
      env: {
        NODE_ENV: 'development',
        TZ: 'UTC',
        VITE_API_URL: 'http://127.0.0.1:5572'
      }
    }
  ]
};
